function cleanPlays(){$(".plays .break").each(function(i){$(this).remove();})
$(".plays div").each(function(i){$(this).css("margin-right","15px");})
$(".visible").each(function(i){var remainder=(i+ 1)%3;if(remainder===0){$(this).css("margin-right","0");$(this).after("<br class='break' style='clear:both;' />");}})}
$(document).ready(function(){if($.cookie("opb_legs")){$(".subnav-plays-legs").toggle();}else{$(".subnav-plays-skill").toggle();}
cleanPlays();equalHeight($(".panel-in"));$("#filter-dd input").each(function(i){$(this).attr('checked',true);});$(".subnav-plays-link").click(function(){$(".subnav-plays li").removeClass("current");$(".subnav-rookies, .subnav-veterans, .subnav-seasoned-veterans, .subnav-all-stars, .subnav-all-plays-skill, .subnav-all-plays-leg, .subnav-one-leg, .subnav-two-leg, .subnav-three-leg, .subnav-four-leg").css("background-image","url(/media/images/bg_plays.png)").css("background-color","#9c9c9c");$(".subnav-rookies .subnav-plays-link, .subnav-veterans .subnav-plays-link, .subnav-seasoned-veterans .subnav-plays-link, .subnav-all-stars .subnav-plays-link, .subnav-all-plays-skill .subnav-plays-link, .subnav-all-plays-leg .subnav-plays-link, .subnav-one-leg .subnav-plays-link, .subnav-two-leg .subnav-plays-link, .subnav-three-leg .subnav-plays-link, .subnav-four-leg .subnav-plays-link").css("background-image","url(/media/images/bg_max.png)");var subnavClass="."+ $(this).attr("href").substring(1);if($(subnavClass+" ul").css("display")=="none"){$(this).parent().addClass("current");$(subnavClass).css("background-image","url(/media/images/bg_gradient_grey.png)").css("background-color","#242A2C");$(subnavClass).find(".subnav-plays-link").css("background-image","url(/media/images/bg_min.png)");$(".subnav-plays-in li ul").hide();$(subnavClass+" ul").show();}else{$(subnavClass+" ul").hide();}
return false;});$("#filter-dd a").click(function(){$("#filter-dd ul").toggle();return false;});$(".dd-bullish input").live("click",function(){if($(".dd-bullish input").attr('checked')){$(".plays .bullish").removeClass("hidden").addClass("visible");}else{$(".plays .bullish").removeClass("visible").addClass("hidden");}
cleanPlays();});$(".dd-bearish input").live("click",function(){if($(".dd-bearish input").attr('checked')){$(".plays .bearish").removeClass("hidden").addClass("visible");}else{$(".plays .bearish").removeClass("visible").addClass("hidden");}
cleanPlays();});$(".dd-neutral input").live("click",function(){if($(".dd-neutral input").attr('checked')){$(".plays .neutral").removeClass("hidden").addClass("visible");}else{$(".plays .neutral").removeClass("visible").addClass("hidden");}
cleanPlays();});$(".dd-question input").live("click",function(){if($(".dd-question input").attr('checked')){$(".plays .question").removeClass("hidden").addClass("visible");}else{$(".plays .question").removeClass("visible").addClass("hidden");}
cleanPlays();});$(".subnav-legs-link").click(function(){var date=new Date();date.setTime(date.getTime()+(3*24*60*60*1000));$.cookie('opb_legs','true',{path:'/',expires:10});$(".subnav-plays-legs, .subnav-plays-skill").toggle();return false;});$(".subnav-skill-link").click(function(){$.cookie('opb_legs',null,{path:'/',expires:10});$(".subnav-plays-legs, .subnav-plays-skill").toggle();return false;});});